version: '3.7'
services:
    project:
      build: .
      restart: always
      volumes:
        - ./:/usr/src/app
      expose:
        - 80
      ports:
        - 8467:80
      command: "gunicorn --chdir /usr/src/app --access-logfile - --error-logfile - --bind :80 project.wsgi:application"
      networks:
        - services
networks:
  services:
    name: services
